### ISSUE TITLE
Sony Harsh Transitions and Low Exposure

### ISSUE THREAD

**Issue by carsonaberle** [jcelaya/hdrmerge#117] opened 2018-03-08 17:48 UTC
I have seen this issue a few times, but I wanted to update with my latest issue. Below is a link to a HDR image and its inputs. They are taken using a Sony A7sii and show in 14 but uncompressed raw (ARW) format. As you can see the two photos have some pretty harsh transitions around the edges. 

If I increase the blur quite a bit on save it helps, but also then introduces noise around the lamp in the back corner of the image.

Lastly as you can see the images start at a very low exposure. Then when taken into Lightroom you have to crank the exposure all the way up and highlights all the way down to preserve the windows. Is there any way to increase the brightness of the image output so I don't have to crank the exposure so much?

All of my outputs are dark and I have to raise the exposure to +5 in Lightroom in order to get them to proper brightness. If you need more test images or more examples of images causing these issues please let me know.

https://drive.google.com/drive/folders/1tMIVYYbs7P0ARUSIPdXsFmY4pcCvqy68?usp=sharing

**Comment by Beep6581** [comment] 2018-03-09 01:10
Confirmed in `v0.5.0-50-g`864968c.
Duplicate of #6

**Closed by Beep6581** 2018-03-09 01:10 UTC
