### ISSUE TITLE
Cannot build in ubuntu 16.04

### ISSUE THREAD

**Issue by FM33** [jcelaya/hdrmerge#84] opened 2016-04-24 17:47 UTC
Hello,

It used to work in trusty but no more in xenial : 
~/Programmes/hdrmerge/build$ cmake -DCMAKE_INSTALL_PREFIX=/home/fabien/Programmes/hdrmerge/release/ ..
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fabien/Programmes/hdrmerge/build

~/Programmes/hdrmerge/build$ make install
[  2%] Generating hdrmerge_es.qm
Updating '/home/fabien/Programmes/hdrmerge/build/hdrmerge_es.qm'...
    Generated 96 translation(s) (96 finished and 0 unfinished)
[  4%] Generating qrc_translations.cxx
[  6%] Generating qrc_resources.cxx
Scanning dependencies of target hdrmerge-objects
[  9%] Building CXX object CMakeFiles/hdrmerge-objects.dir/Image.cpp.o
[ 11%] Building CXX object CMakeFiles/hdrmerge-objects.dir/ImageStack.cpp.o
[ 13%] Building CXX object CMakeFiles/hdrmerge-objects.dir/Bitmap.cpp.o
[ 15%] Building CXX object CMakeFiles/hdrmerge-objects.dir/RawParameters.cpp.o
[ 18%] Building CXX object CMakeFiles/hdrmerge-objects.dir/EditableMask.cpp.o
[ 20%] Building CXX object CMakeFiles/hdrmerge-objects.dir/DngFloatWriter.cpp.o
[ 22%] Building CXX object CMakeFiles/hdrmerge-objects.dir/TiffDirectory.cpp.o
[ 25%] Building CXX object CMakeFiles/hdrmerge-objects.dir/BoxBlur.cpp.o
[ 27%] Building CXX object CMakeFiles/hdrmerge-objects.dir/ExifTransfer.cpp.o
[ 29%] Building CXX object CMakeFiles/hdrmerge-objects.dir/ImageIO.cpp.o
/home/fabien/Programmes/hdrmerge/ImageIO.cpp: In static member function ‘static hdrmerge::Image hdrmerge::ImageIO::loadRawImage(hdrmerge::RawParameters&)’:
/home/fabien/Programmes/hdrmerge/ImageIO.cpp:42:42: error: ‘LIBRAW_DECODER_FLATFIELD’ was not declared in this scope
         if(!decoder_info.decoder_flags & LIBRAW_DECODER_FLATFIELD) {
                                          ^
CMakeFiles/hdrmerge-objects.dir/build.make:298 : la recette pour la cible « CMakeFiles/hdrmerge-objects.dir/ImageIO.cpp.o » a échouée
make[2]: *** [CMakeFiles/hdrmerge-objects.dir/ImageIO.cpp.o] Erreur 1
CMakeFiles/Makefile2:67 : la recette pour la cible « CMakeFiles/hdrmerge-objects.dir/all » a échouée
make[1]: *** [CMakeFiles/hdrmerge-objects.dir/all] Erreur 2
Makefile:127 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

**Comment by FM33** [comment] 2016-05-05 16:00
I had a little time to dig into it. I found this : 
https://github.com/OpenImageIO/oiio/issues/1203
I am not a coder but I tried the same thing : Edited ImageIO.cpp and removed the line at position 42 and also a "else" and a "}" trying not to break the if block.
It worked !!
Like the comment on the link, I don't know if "that has unintended runtime consequences". It seems to work fine...

**Comment by Beep6581** [comment] 2016-08-09 19:21
Duplicate of #85 , fixed.

**Closed by Beep6581** 2016-08-09 19:21 UTC
