### ISSUE TITLE
Green color where mask was manually adjusted

### ISSUE THREAD

**Issue by alexforencich** [jcelaya/hdrmerge#107] opened 2017-06-04 14:50 UTC
I made a few manual adjustments to the masks to remove some ghosting (replaced blue layer (+2 EV) with green layer (+4 EV) in a few isolated spots) and the result was that the pixels that corresponded to the changed mask turned a nasty shade of green.  

![hdrmerge-green](https://cloud.githubusercontent.com/assets/508807/26762618/1e9219fa-48fa-11e7-91b9-b039a45aec6d.png)

I'm running the latest git version of hdrmerge.

**Comment by Beep6581** [comment] 2017-06-04 15:27
@alexforencich duplicate of #64 ?

**Closed** 2018-06-19 07:23 UTC
