### ISSUE TITLE
Median blending RAWs

### ISSUE THREAD

**Issue by simontheflutist** [jcelaya/hdrmerge#76] opened 2015-11-12 03:59 UTC
I'd love to see if HDRmerge could work to do a median blend of undemosaiced RAW files pixel by pixel so as to simplify a median workflow (work on a single RAW as opposed to process a bunch of RAWs then do median of image files).

[It's been suggested on HDRmerge](https://github.com/jcelaya/hdrmerge/issues/60) before slightly differently. I was told to submit the feature request here after I did at [RawTherapee](https://github.com/Beep6581/RawTherapee/issues/2887) because it seems that HDRmerge already has most of the process (data structures and I/O) RAW manipulation. I am sure that astrophotographers  and people who want to do things like removing moving objects would appreciate the ability to perform the median operation at the RAW level.

In addition to median, geometric mean would be nice (so as to be invariant under gamma).

**Comment by Beep6581** [comment] 2017-11-22 21:57
Duplicate of #60

**Closed by Beep6581** 2017-11-22 21:57 UTC
