### ISSUE TITLE
Unexpected Results

### ISSUE THREAD

**Issue by nvki** [jcelaya/hdrmerge#158] opened 2018-07-26 18:14 UTC
I'm having an issue with reddish artifacts in overexposed parts of my image. The cause might be the initial automatic layering not working as expected, causing auready blown out areas to be overexposed. Not sure if the reason is the kind of bracketing (mixed aperture and speed) or maybe the misalignment being too bad (handheld shot). I am using v0.5.0 on Win10 x64, please see the attached image and RAW files for more detailes information.

[Raw Files](https://drive.google.com/open?id=1_hFidzXgK7kbZsN5eM4tIO8ee7m37DqE)

![merge_issue](https://user-images.githubusercontent.com/25460636/43280129-4cbf48c0-9110-11e8-897d-7984f536cac9.jpg)

**Comment by Beep6581** [comment] 2018-07-26 19:03
The cause was most likely wrong white levels. The issue is now fixed. It will be part of the next release, which we really should get around to releasing soon.

DNG from the latest HDRMerge + JPG + PP3 (RawTherapee):
https://filebin.net/r475arwgdeqtizul

Compiling the latest HDRMerge code in Linux is easy, while in Windows it requires a bit more fiddling:
https://github.com/jcelaya/hdrmerge/blob/master/INSTALL.md

In addition to the bad misalignment, I noticed that you bracketed by changing not only exposure time but also aperture. Bracketing by changing aperture will often lead to bad results because changing aperture changes the depth of field and the image geometry. Bracket using only exposure.

**Closed by Beep6581** 2018-07-26 19:03 UTC

**Comment by nvki** [comment] 2018-07-26 19:09
Thank you for your quick reply! I'll be looking forward to the next release then as I'm not sure how successful I'll be compiling it myself ;)
I know that aperture bracketing is bad and ideally i'd just change the shutter speed with the cam on a tripod. I took this one walking by in a hurry and unfortunately the camera was in program mode.
